### ISSUE TITLE
Not able to deploy lambda function & stepfunction getting error Serverless plugin "serverless-step-functions" initialization errored: Unexpected token [ 

### ISSUE THREAD

**Issue by anudeepsinghpatelgithub** [horike37/serverless-step-functions#176]
serverless deploy --region us-west-2 --verbose
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
 
  Syntax Error -------------------------------------------
 
  Unexpected token [
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
SyntaxError: Unexpected token [
SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (<somevalue>/node_modules/serverless-step-functions/lib/index.js:7:23)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /node_modules/serverless/lib/classes/PluginManager.js:99:24
    at Array.forEach (native)
    at PluginManager.loadPlugins (node_modules/serverless/lib/classes/PluginManager.js:97:13)
    at PluginManager.loadServicePlugins (node_modules/serverless/lib/classes/PluginManager.js:150:10)
    at PluginManager.loadAllPlugins (node_modules/serverless/lib/classes/PluginManager.js:93:10)
    at node_modules/serverless/lib/Serverless.js:70:26
    at tryCatcher (node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (node_modules/serverless/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (node_modules/serverless/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (node_modules/serverless/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (node_modules/serverless/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (node_modules/serverless/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (node_modules/serverless/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (node_modules/serverless/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (node_modules/serverless/node_modules/bluebird/js/release/async.js:17:14)
From previous event:
    at Serverless.init (node_modules/serverless/lib/Serverless.js:68:8)
    at node_modules/serverless/bin/serverless:42:21
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at node_modules/serverless/bin/serverless:28:46
    at Object.<anonymous> (node_modules/serverless/bin/serverless:67:4)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           4.2.2
     Serverless Version:     1.38.0
 
Build step 'Execute shell' marked build as failure
Notifying upstream projects of job completion
Finished: FAILURE

**Comment by theburningmonk** [comment]
Can you paste your step function definition from the `serverless.yml` here?

**Comment by theburningmonk** [comment]
@anudeepsinghpatelgithub ping ping ;-)

**Comment by anudeepsinghpatelgithub** [comment]
Hi,
I am so sorry but my issue is fixed after changing the node version. I was facing issue with Node version4.2.2 and when I upgraded to latest lts versioni.e. 10.X.x
It's started working.

Thanks a lot and sorry for inconvenient.

**Comment by anudeepsinghpatelgithub** [comment]
Hi,
I am so sorry but my issue is fixed after changing the node version. I was facing issue with Node version4.2.2 and when I upgraded to latest lts versioni.e. 10.X.x
It's started working.

Thanks a lot and sorry for inconvenient.

**Comment by theburningmonk** [comment]
@anudeepsinghpatelgithub no worries! glad it's all working for you 👍

**Comment by bweigel** [comment]
Same issue (Node 8) and same fix (Node 10) :+1:
