### ISSUE TITLE
Adding step functions to existing project fails with undefined error

### ISSUE THREAD

**Issue by justinmchase** [horike37/serverless-step-functions#35]
I'm updating to `v1.0.0` and I hit an error where its trying to, presumably, update step functions in an existing stack that I have previously deployed but the step functions don't yet exist in that stack.

```
  Type Error ---------------------------------------------

     Cannot read property 'forEach' of undefined

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

TypeError: Cannot read property 'forEach' of undefined
    at _.forEach (/Users/justin/code/input-system/node_modules/serverless-step-functions/lib/index.js:140:29)
    at arrayEach (/Users/justin/code/input-system/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/Users/justin/code/input-system/node_modules/lodash/lodash.js:9359:14)
    at ServerlessStepFunctions.display (/Users/justin/code/input-system/node_modules/serverless-step-functions/lib/index.js:138:7)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at PluginManager.invoke (/Users/justin/code/input-system/node_modules/serverless/lib/classes/PluginManager.js:210:22)
    at PluginManager.run (/Users/justin/code/input-system/node_modules/serverless/lib/classes/PluginManager.js:225:17)
    at Serverless.run (/Users/justin/code/input-system/node_modules/serverless/lib/Serverless.js:97:31)
    at serverless.init.then (/Users/justin/code/input-system/node_modules/serverless/bin/serverless:23:50)
```

**Comment by horike37** [comment]
@justinmchase
Thanks for the opening again!
I also have reproduced it and fixed. Then just released new version.
https://github.com/horike37/serverless-step-functions/releases/tag/1.0.2

Please update and try again.

**Comment by justinmchase** [comment]
I was just about to send you a pull request that looked almost the same :)

Thanks for the quick fixes.

**Comment by justinmchase** [comment]
I tried updating but it looks like 1.0.2 hasn't been published to npm yet.

**Comment by horike37** [comment]
Sorry.. Just published to npm.
Please try again.
https://www.npmjs.com/package/serverless-step-functions

**Comment by justinmchase** [comment]
Worked 👍
