### ISSUE TITLE
v1.0.2 not showing commands 

### ISSUE THREAD

**Issue by rizowski** [horike37/serverless-step-functions#42]
I have been trying to upgrade our latest project to use serverless `v1.11.0` with serverless-step-functions (SSF) `v1.0.2` from `v0.4.0`. If I try to upgrade SSF to `v1.0.2`/latest it no longer shows the command `serverless deploy stepf`. 

Here is the output of running `serverless`

```
Commands
* Serverless documentation: http://docs.serverless.com
* You can run commands with "serverless" or the shortcut "sls"
* Pass "--help" after any <command> for contextual help

config credentials ............ Configures a new provider profile for the Serverless Framework
create ........................ Create new Serverless service
install ....................... Install a Serverless service from GitHub
deploy ........................ Deploy a Serverless service
deploy function ............... Deploy a single function from the service
deploy list ................... List deployed version of your Serverless Service
invoke ........................ Invoke a deployed function
invoke local .................. Invoke function locally
invoke stepf .................. Invoke Step functions
info .......................... Display information about the service
logs .......................... Output the logs of a deployed function
metrics ....................... Show metrics for a specific function
remove ........................ Remove Serverless service and all resources
rollback ...................... Rollback the Serverless service to a specific deployment
slstats ....................... Enable or disable stats

Plugins
AwsCompileAlexaSkillEvents, AwsCompileApigEvents, AwsCompileCloudWatchEventEvents, AwsCompileCloudWatchLogEvents, AwsCompileFunctions, AwsCompileIoTEvents, 
AwsCompileS3Events, AwsCompileSNSEvents, AwsCompileScheduledEvents, AwsCompileStreamEvents, AwsConfigCredentials, AwsDeploy, AwsDeployFunction, AwsDeployList,
 AwsInfo, AwsInvoke, AwsInvokeLocal, AwsLogs, AwsMetrics, AwsProvider, AwsRemove, AwsRollback, Config, Create, Deploy, Info, Install, Invoke, Logs, Metrics, Package, Plugin, Remove,
 Rollback, ServerlessStepFunctions, SlStats
```

As you can see `ServerlessStepFunctions` is registered as a plugin but isn't listed under the deploy section of commands.

```
> serverless deploy stepf statemachines --stage $NODE_ENV -n


  Serverless Error ---------------------------------------

     Command "deploy stepf" not found, Run "serverless help"
     for a list of all available commands.

  Stack Trace --------------------------------------------

ServerlessError: Command "deploy stepf" not found, Run "serverless help" for a list of all available commands.
    at _.reduce (/Users/colton/git/vs/fusion2.0/etl/node_modules/serverless/lib/classes/PluginManager.js:176:13)
    at arrayReduce (/Users/colton/git/vs/fusion2.0/etl/node_modules/serverless/node_modules/lodash/lodash.js:704:21)
    at Function.reduce (/Users/colton/git/vs/fusion2.0/etl/node_modules/serverless/node_modules/lodash/lodash.js:9683:14)
    at PluginManager.getCommand (/Users/colton/git/vs/fusion2.0/etl/node_modules/serverless/lib/classes/PluginManager.js:166:14)
    at PluginManager.validateCommand (/Users/colton/git/vs/fusion2.0/etl/node_modules/serverless/lib/classes/PluginManager.js:233:10)
    at Serverless.run (/Users/colton/git/vs/fusion2.0/etl/node_modules/serverless/lib/Serverless.js:83:24)
    at serverless.init.then (/Users/colton/git/vs/fusion2.0/etl/node_modules/serverless/bin/serverless:23:50)
From previous event:
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
From previous event:
    at __dirname (/Users/colton/git/vs/fusion2.0/etl/node_modules/serverless/bin/serverless:15:28)
    at Object.<anonymous> (/Users/colton/git/vs/fusion2.0/etl/node_modules/serverless/bin/serverless:27:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       6.10.1
     Serverless Version: 1.11.0
```

**Comment by horike37** [comment]
Thank you for the opening @rizowski !
I have supported `serverless deploy stepf` command no longer since v1.0.
However, it was possible that you can deploy your stepfunctions via `serverless deploy` since v1.0. 
Please try again it with using `serverless deploy`.

**Comment by rizowski** [comment]
Ah, I didn't see that you had removed the command.

I'm still not seeing my step functions being deployed.
If I run `sls deploy -ns test` and check the local output I can see there is json for the step functions. But when I run a deploy and then go to aws I don't see them in the step functions section. Any ideas? 
Based on the documentation in the current readme the only thing I had to do is change:
```yml
stepFunctions:
  stateMachines:
    my-step:
      comment: 'something cool'
      StartAt: 'something'
      States:
        # ...
```
To
```yml
stepFunctions:
  stateMachines:
    my-step:
      definition:
        comment: 'something cool'
        StartAt: 'something'
        States:
          # ...
```
Is that right or was there more that could be causing issues?

**Comment by horike37** [comment]
@rizowski 
As I saw, your syntax is rights in serverless.yml.
If you saw successfully response in your local output after run `sls deploy`, it seems like that you saw AWS Account or region by mistake. Could you check this again?

**Comment by rizowski** [comment]
@horike37 I know the region is correct because I can revert the version back to 0.4 and it deploys fine.

**Comment by horike37** [comment]
@rizowski 
Hmm 🤔 Cloud you please provide me with serverless.yml which you use? I would like to run it on my local machine.
