### ISSUE TITLE
step function does not get created

### ISSUE THREAD

**Issue by kaiser14** [horike37/serverless-step-functions#70]
Issue: step function does not get created, but lambda function does get created. No errors are thrown. 

sls deploy:
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
.....
Serverless: Stack create finished...
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading function .zip files to S3...
Serverless: Uploading service .zip file to S3 (5.53 MB)...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
...............
Serverless: Stack update finished...
Service Information
service: step-functions-3
stage: dev
region: us-west-2
api keys:
  None
endpoints:
  None
functions:
  hello: step-functions-3-dev-hello
Serverless StepFunctions OutPuts
endpoints:

[serverless.yml.zip](https://github.com/horike37/serverless-step-functions/files/1184386/serverless.yml.zip)

**Comment by kaiser14** [comment]
The generated cloudformation has no definitions for step-functions. I can attach that if needed.

**Comment by horike37** [comment]
Thank you for opening up and showing me your serverless,yml @kaiser14 !
I found a wrong point in a indent of `- http` block in your serverless,yml.
```yml
- http:
  path: gofunction
  method: GET
```

you need a space before `path` and `method`. 
Here is the correct sample.
```yml
- http:
    path: gofunction
    method: GET
```

Please try again?

**Comment by kaiser14** [comment]
Sorry, I intentionally did that to see if the deploy would break and throw an error. There are no errors even with incorrect whitespaces

**Comment by kaiser14** [comment]
I think the plugin is not getting invoked?

**Comment by horike37** [comment]
Umm. I have tried that using your yaml file, but I deployed successfully.
The behavior which occurs no errors is a little weired..

Are you using lastet version with sls core and the plugin?

**Comment by kaiser14** [comment]
sls version: 1.11.0
serverless-step-functions: "^1.1.0"

**Comment by horike37** [comment]
sls is not latest version. Could you please update sls core to v1.18.1?

**Comment by kaiser14** [comment]
Thank you. I'll update node, sls and try again.

**Comment by kaiser14** [comment]
I now have more meaningful debug logs:
TypeError: Cannot read property 'path' of null
    at ServerlessStepFunctions.getHttpPath (/Users/xpp7/code/serverless/step-functions-3/node_modules/serverless-step-functions/lib/deploy/events/apiGateway/validate.js:66:20)
    at _.forEach (/Users/xpp7/code/serverless/step-functions-3/node_modules/serverless-step-functions/lib/deploy/events/apiGateway/validate.js:15:28)
    at arrayEach (/Users/xpp7/code/serverless/step-functions-3/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/Users/xpp7/code/serverless/step-functions-3/node_modules/lodash/lodash.js:9359:14)
    at _.forEach (/Users/xpp7/code/serverless/step-functions-3/node_modules/serverless-step-functions/lib/deploy/events/apiGateway/validate.js:12:9)
    at arrayEach (/Users/xpp7/code/serverless/step-functions-3/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/Users/xpp7/code/serverless/step-functions-3/node_modules/lodash/lodash.js:9359:14)
    at ServerlessStepFunctions.httpValidate (/Users/xpp7/code/serverless/step-functions-3/node_modules/serverless-step-functions/lib/deploy/events/apiGateway/validate.js:10:7)
    at Object.package:compileEvents [as hook] (/Users/xpp7/code/serverless/step-functions-3/node_modules/serverless-step-functions/lib/index.js:95:41)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:218:55)

**Comment by kaiser14** [comment]
http.path is somehow being returned as 'null'

**Comment by kaiser14** [comment]
Please ignore last comment. I realized i made a mistake. Trying again now...

**Comment by kaiser14** [comment]
It worked. StepFunction got created and i have an api gateway endpoint. Updating to latest node and sls versions resolved my problem. Thank you for your help!

**Comment by horike37** [comment]
Glad to hear that solved your ploblem!
