### ISSUE TITLE
deploy fails with node 6.9.2.  that.sdk[service] is not a constructor

### ISSUE THREAD

**Issue by marc-at** [horike37/serverless-step-functions#8]
I am receiving the following error:

> sls deploy stepf --state stepFuncSteps -v
Serverless: Start to deploy stepFuncSteps step function...

  Type Error ---------------------------------------------

     that.sdk[service] is not a constructor

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

TypeError: that.sdk[service] is not a constructor
    at persistentRequest (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:149:26)
    at doCall (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:134:9)
    at BbPromise (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:145:14)
    at Promise._execute (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/debuggability.js:299:9)
    at Promise._resolveFromExecutor (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:77:14)
    at persistentRequest (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:132:38)
    at AwsProvider.request (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:148:12)
    at ServerlessStepFunctions.deleteStateMachine (/Users/marc/dev/message-step-functions/node_modules/serverless-step-functions/index.js:307:26)
    at ServerlessStepFunctions.tryCatcher (/Users/marc/dev/message-step-functions/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/marc/dev/message-step-functions/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/marc/dev/message-step-functions/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/marc/dev/message-step-functions/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/marc/dev/message-step-functions/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/marc/dev/message-step-functions/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/marc/dev/message-step-functions/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/marc/dev/message-step-functions/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

     Please report this error. We think it might be a bug.

  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       6.9.2
     Serverless Version: 1.3.0

**Comment by horike37** [comment]
@marc-at 
Thank you for using and reporting!
Sorry the plugin can't work with Serverless v1.3  or lower. Please update Serverless latest version 1.5, try again.

**Comment by marc-at** [comment]
Thanks.  Upgrading serverless worked.  I appreciate all your work.  I'll close this ticket.
